package main

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

const bulkTemplateSrc = `// Code generated by sqlc-bulk-plugin. DO NOT EDIT.

package {{.Package}}

import (
	"context"
{{- if .HasPgtype}}
	"github.com/jackc/pgx/v5/pgtype"
{{- end}}
)
{{range .Queries}}
{{if not .UseModelStruct}}
type {{.ItemStruct}} struct {
{{- range .Fields}}
	{{.ItemFieldName}} {{.GoType}}
{{- end}}
}
{{end}}
func (q *Queries) {{.FuncName}}(ctx context.Context, items []{{if .UseModelStruct}}{{.ModelStruct}}{{else}}{{.ItemStruct}}{{end}}) error {
	params := {{.ParamsStruct}}{
{{- range .Fields}}
		{{.ParamsField}}: make([]{{.ParamsElemType}}, len(items)),
{{- end}}
	}
	for i, item := range items {
{{- range .Fields}}
		params.{{.ParamsField}}[i] = {{.ConvertExpr}}
{{- end}}
	}
	return q.{{.QueryName}}(ctx, params)
}
{{end}}
type BulkQuerier interface {
{{- range .Queries}}
	{{.FuncName}}(ctx context.Context, items []{{if .UseModelStruct}}{{.ModelStruct}}{{else}}{{.ItemStruct}}{{end}}) error
{{- end}}
}

var _ BulkQuerier = (*Queries)(nil)
`

type templateData struct {
	Package   string
	Queries   []bulkQuery
	HasPgtype bool
}

func renderTemplate(pkg string, queries []bulkQuery) ([]byte, error) {
	tmpl, err := template.New("bulk").Parse(bulkTemplateSrc)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	data := templateData{
		Package:   pkg,
		Queries:   queries,
		HasPgtype: needsPgtype(queries),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n\nGenerated code:\n%s", err, buf.String())
	}

	return formatted, nil
}
