package main

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"
)

// itemType is a template helper that returns the item type for a query.
func itemType(q bulkQuery) string {
	if q.UseModelStruct {
		return q.ModelStruct
	}
	return q.ItemStruct
}

// returnSig returns the return signature for the adapter function.
func returnSig(q bulkQuery) string {
	if q.ReturnType != "" {
		return "(" + q.ReturnType + ", error)"
	}
	return "error"
}

const bulkTemplateSrc = `// Code generated by sqlc-bulk-plugin. DO NOT EDIT.

package {{.Package}}

import (
	"context"
{{- if .HasPgtype}}
	"github.com/jackc/pgx/v5/pgtype"
{{- end}}
)
{{range .Queries}}
{{if not .UseModelStruct}}
type {{.ItemStruct}} struct {
{{- range .Fields}}
	{{.ItemFieldName}} {{.GoType}}
{{- end}}
}
{{end}}
// {{.FuncName}} converts a slice of {{itemType .}} into {{.ParamsStruct}} and calls {{.QueryName}}.
{{- if eq $.Style "function"}}
{{- if $.EmitInterface}}
func {{.FuncName}}(ctx context.Context, q Querier, items []{{itemType .}}) {{returnSig .}} {
{{- else}}
func {{.FuncName}}(ctx context.Context, q *Queries, items []{{itemType .}}) {{returnSig .}} {
{{- end}}
{{- else}}
func (q *Queries) {{.FuncName}}(ctx context.Context, items []{{itemType .}}) {{returnSig .}} {
{{- end}}
	params := {{.ParamsStruct}}{
{{- range .Fields}}
		{{.ParamsField}}: make([]{{.ParamsElemType}}, len(items)),
{{- end}}
	}
	for i, item := range items {
{{- range .Fields}}
		params.{{.ParamsField}}[i] = {{.ConvertExpr}}
{{- end}}
	}
	return q.{{.QueryName}}(ctx, params)
}
{{end}}
{{- if eq .Style "interface"}}
type BulkQuerier interface {
	Querier
{{- range .Queries}}
	{{.FuncName}}(ctx context.Context, items []{{itemType .}}) {{returnSig .}}
{{- end}}
}

var _ BulkQuerier = (*Queries)(nil)
{{- end}}
`

type templateData struct {
	Package       string
	Style         string
	EmitInterface bool
	Queries       []bulkQuery
	HasPgtype     bool
}

func renderTemplate(pkg string, style string, emitInterface bool, queries []bulkQuery) ([]byte, error) {
	funcMap := template.FuncMap{
		"itemType":  itemType,
		"returnSig": returnSig,
	}
	tmpl, err := template.New("bulk").Funcs(funcMap).Parse(bulkTemplateSrc)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}

	data := templateData{
		Package:       pkg,
		Style:         style,
		EmitInterface: emitInterface,
		Queries:       queries,
		HasPgtype:     needsPgtype(queries),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n\nGenerated code:\n%s", err, buf.String())
	}

	return formatted, nil
}
